runtime: python37

instance_class: B2

env_variables:
  PORT: 8080
  FLASK_ENV: appengine

entrypoint: gunicorn -b :$PORT "matcher.service:create_app()"

basic_scaling:
  max_instances: 5
  idle_timeout: 5m
