# OpenReview Matcher CircleCI 2.0 configuration file 28
version: 2.1

parameters:
  openreview-api-v1-branch:
    type: string
    default: "master"
  openreview-api-v2-branch:
    type: string
    default: "main"

jobs:
  build:
    working_directory: ~/
    docker:
    - image: circleci/python:3.7-node
    - image: circleci/redis:6.0.0
    - image: circleci/mongo:4.4.5
      command: [--replSet,rs0]
    - image: docker.elastic.co/elasticsearch/elasticsearch:7.7.0
      environment:
        xpack.security.enabled: false
        transport.host: localhost
    steps:
    - checkout:
        path: ~/openreview-matcher-repo
    - run:
        name: Initialize Replica Set
        command: |
          wget -qO - https://www.mongodb.org/static/pgp/server-4.4.asc | sudo apt-key add -
          sudo touch /etc/apt/sources.list.d/mongodb-org-4.4.list
          echo "deb [ arch=amd64,arm64 ] https://repo.mongodb.org/apt/ubuntu bionic/mongodb-org/4.4 multiverse" | sudo tee /etc/apt/sources.list.d/mongodb-org-4.4.list
          sudo apt-get update
          sudo apt-get install -y mongodb-org=4.4.5 mongodb-org-server=4.4.5 mongodb-org-shell=4.4.5 mongodb-org-mongos=4.4.5 mongodb-org-tools=4.4.5
          mongo mongodb://localhost:27017 --eval "rs.initiate()"
    - run: git clone https://$OPENREVIEW_GITHUB@github.com/openreview/openreview-api-v1.git ~/openreview
    - run: cd ~/openreview && git checkout << pipeline.parameters.openreview-api-v1-branch >>
    - run: git clone https://$OPENREVIEW_GITHUB@github.com/openreview/openreview-api.git ~/openreview-v2
    - run: cd ~/openreview-v2 && git checkout << pipeline.parameters.openreview-api-v2-branch >>
    - run: git clone https://$OPENREVIEW_GITHUB@github.com/openreview/openreview-py.git ~/openreview-py
    - run: mkdir ~/openreview/logs
    - run: mkdir ~/openreview/files
    - run: mkdir ~/openreview/files/attachments
    - run: mkdir ~/openreview/files/pdfs
    - run: mkdir ~/openreview/files/temp
    - run: mkdir ~/openreview-v2/logs
    - run: mkdir ~/openreview-v2/files
    - run: mkdir ~/openreview-v2/files/attachments
    - run: mkdir ~/openreview-v2/files/pdfs
    - run: mkdir ~/openreview-v2/files/temp
    - run:
        name: setup virtual environment
        command: |
          python -m venv matcher
    - run:
        name: install dependencies
        command: |
          source matcher/bin/activate
          cd ~/openreview-matcher-repo
          pip install -e .
    - run:
        name: install the local openreview-py as a dependency
        command: |
          source matcher/bin/activate
          cd ~/openreview-matcher-repo
          pip install -e ~/openreview-py
    - run:
        name: install api-v1
        command: |
          cd ~/openreview
          npm install
    - run:
        name: run api-v1
        command: |
          source matcher/bin/activate
          cd ~/openreview
          NODE_ENV=circleci node scripts/clean_start_app.js
        background: true
    - run:
        name: install api-v2
        command: |
          cd ~/openreview-v2
          npm install
    - run:
        name: run api-v2
        command: |
          source matcher/bin/activate
          cd ~/openreview-v2
          NODE_ENV=circleci node scripts/setup_app.js
        background: true
    - run:
        shell: /bin/sh
        command: |
          wget --retry-connrefused --waitretry=1 --read-timeout=20 --timeout=15 -t 10 http://localhost:3000
          :
    - run:
        shell: /bin/sh
        command: |
          wget --retry-connrefused --waitretry=2 --read-timeout=20 --timeout=15 -t 20 http://localhost:3001
          :
    - run:
        name: run tests
        command: |
          source matcher/bin/activate
          cd ~/openreview-matcher-repo
          mkdir reports
          mkdir reports/pytest
          python -m pytest -x tests --junitxml=reports/pytest/pytest-report.xml
    - store_test_results:
        path: reports
    - store_artifacts:
        path: reports
